### ISSUE TITLE
Weird behavior with stroke

### ISSUE THREAD

**Issue by perroudsky** [tienphaw/react-native-figma-squircle#15]
Hello!

The stroke doesn't look right both on ios and android.
I've made tests with different rectangle sizes; sometimes it is defaulted, sometimes not.

- ios exemple (look at right side)

<img width="403" alt="Capture d’écran 2022-05-23 à 14 50 02" src="https://user-images.githubusercontent.com/25634046/169823433-eb63d33b-199b-482f-845a-65c9ab6ca66f.png">

- same android exemple (bottom)
<img width="412" alt="Capture d’écran 2022-05-23 à 14 49 52" src="https://user-images.githubusercontent.com/25634046/169823558-42dc963a-16a9-40c3-9b6e-f3c52d5f8664.png">

the code :

```javascript
 <SquircleView
    style={{
      width: BUTTONS_WIDTH,
      height: 50,
     }}
    squircleParams={{
     cornerSmoothing: 1,
      cornerRadius: 10,
      strokeWidth: 2,
      strokeColor: "#000",
      fillColor: "#fff",
     }}
    />
<SquircleView
     style={{
      width: BUTTONS_WIDTH,
      height: 50,
     }}
     squircleParams={{
      cornerSmoothing: 0.5,
      cornerRadius: 10,
      fillColor: "pink",
      strokeColor: "red",
      strokeWidth: 2,
     }}
/>
```

**Comment by phamfoo** [comment]
I couldn't reproduce this on my machine. 
<img width="293" alt="Screen Shot 2022-05-23 at 9 06 04 PM" src="https://user-images.githubusercontent.com/57227217/169837827-f2a77a33-d618-4a28-98ee-b979af46a056.png">
Could you provide a [snack](https://snack.expo.dev/) or a GitHub repo that reproduces the problem?

**Comment by perroudsky** [comment]
Thanks for the quick answer !

Turns out its the decimal numbers that's making the stroke buggy

https://snack.expo.dev/@perroudsky/arrogant-blueberries

**Comment by phamfoo** [comment]
Can you try again with `v0.3.3`?

**Comment by perroudsky** [comment]
yep, fixed !
thank you
