### ISSUE TITLE
Help needed with creating squircle buttons

### ISSUE THREAD

**Issue by Abhimanyu-Jha** [tienphaw/react-native-figma-squircle#16]
First off... a great library for creating truly squircle components, thanks a lot for this!
Is it possible to wrap react buttons with this wrapper to get squircle buttons? If yes can you please provide a usage example for the same?

Thanks in advance :)

**Comment by phamfoo** [comment]
You can take a look at the example project
https://github.com/tienphaw/react-native-figma-squircle/blob/3847874be081a927eb8929ea21771c67130ddc2a/example/App.tsx#L77

It's just like how you would normally implement a button, but instead of using `View`, you use `SquircleView`.
