### ISSUE TITLE
Skia support?

### ISSUE THREAD

**Issue by Krisztiaan** [tienphaw/react-native-figma-squircle#18]
Hey,

Just something to consider, if Skia is available for the app, we could just use `Skia.SVG.MakeFromString` or similar, to have a more efficient SVG component?

Skia docs: https://shopify.github.io/react-native-skia/docs/images-svg/#svg-support

**Comment by Kamargis** [comment]
Hello, 

I tried what you suggested and it works fine
```
function SquircleBackground({
  cornerRadius = 0,
  topLeftCornerRadius,
  topRightCornerRadius,
  bottomRightCornerRadius,
  bottomLeftCornerRadius,
  cornerSmoothing,
  fillColor = "#000",
}: SquircleParams) {
  return (
    <Rect style={StyleSheet.absoluteFill}>
      {({ width, height }) => {
        const squirclePath = getSvgPath({
          width,
          height,
          cornerSmoothing,
          cornerRadius,
          topLeftCornerRadius,
          topRightCornerRadius,
          bottomRightCornerRadius,
          bottomLeftCornerRadius,
        });

        const svg = Skia.SVG.MakeFromString(
          `<svg viewBox='0 0 ${width} ${height}' xmlns='http://www.w3.org/2000/svg' fill="${fillColor}">
            <path d='${squirclePath}' />
          </svg>`
        )!;

        return (
          <Canvas style={{ flex: 1 }}>
            <ImageSVG svg={svg} x={0} y={0} width={width} height={height} />
          </Canvas>
        );
      }}
    </Rect>
  );
}
```

When applying the stroke it just render a regular outline that does not follow the shape of the squircle, the final result is not great

In the example above I just removed anything stroke related

**Comment by phamfoo** [comment]
Hey, sorry for the late response. I've been thinking about this. I would just use [figma-squircle](https://github.com/tienphaw/figma-squircle) and the [Path API](https://shopify.github.io/react-native-skia/docs/shapes/path#using-svg-notation) directly. I talked about this more [here](https://github.com/tienphaw/react-native-figma-squircle#before-you-install) in the README.
