### ISSUE TITLE
Exception thrown while executig UI block/updating property 'fill'

### ISSUE THREAD

**Issue by samvoults** [tienphaw/react-native-figma-squircle#19]
I followed the examples after I "npm i react-native-figma-squircle":

![1](https://user-images.githubusercontent.com/58936269/201719451-df315bea-4223-4589-ad24-5a7581b7fa0b.png)

![2](https://user-images.githubusercontent.com/58936269/201719508-517ae028-54b3-4386-af02-bdedc96f2408.png)

But I got this error on my iPhone:

![3](https://user-images.githubusercontent.com/58936269/201719816-d101fddc-6112-4391-a244-21680417b2da.jpg)

And this error on my android:

![314604689_5711426222233844_5019449140610062211_n](https://user-images.githubusercontent.com/58936269/201720218-d5b3f88b-043d-422b-b02e-66799f1d31e9.jpg)

**Comment by phamfoo** [comment]
Hi, could you create a github repo or a [snack](https://snack.expo.io/) for me to look at?

**Comment by samvoults** [comment]
I created a new expo project and it was working.

Maybe the problem I have is because my project having the error is using expo 45 instead of 47. So I'll upgrade my project sooner and come back if I still have the error.

Thanks for your quick response btw.
