### ISSUE TITLE
Export type error { SquircleParams }

### ISSUE THREAD

**Issue by amruu** [tienphaw/react-native-figma-squircle#2]
<img width="1440" alt="Screenshot 2021-07-02 at 11 03 29 PM" src="https://user-images.githubusercontent.com/18157104/124310425-c6f6d600-db89-11eb-8074-a364201d3a9c.png">

<b>it shows me this error when i tried to use squircle as per your documentation on github<b/>

**Comment by amruu** [comment]
it'd be great help if this issue can be solved soon, i think the error is from your internal files

**Comment by phamfoo** [comment]
Similar issue https://github.com/react-navigation/react-navigation/issues/7978#issuecomment-614766724
Can you try upgrading `@babel/core` and `@babel/runtime` @amruu?

**Comment by amruu** [comment]
Yes it did work when i tried in other project which had higher version of `@babel/core`

**Comment by amruu** [comment]
Yes it did work when i tried in other project which had higher version of @babel/core @tienphaw

**Comment by amruu** [comment]
Yes it did work when i tried in other project which had higher version of `@babel/core` @tienphaw
