### ISSUE TITLE
Apply border Bottom/Top/Left/Right Radius 

### ISSUE THREAD

**Issue by BenRx** [tienphaw/react-native-figma-squircle#3]
Greetings!
I am looking for a to use your library in order to apply a border radius (with smoothing) only at the top or bottom of the component.
it actually possible ?

Thanks for your work!

**Comment by phamfoo** [comment]
It's not implemented yet. I'll probably add this to a future release though.
I'll leave the issue open for now.

**Comment by phamfoo** [comment]
This has been implemented, can you install `v0.2.0` and give it a try @BenRx?
You can take a look at the new params here https://github.com/tienphaw/react-native-figma-squircle#topleftcornerradius
