### ISSUE TITLE
Does not play nice with PlatformColor

### ISSUE THREAD

**Issue by cloudorbush** [tienphaw/react-native-figma-squircle#4]
I get the following error:
 
 ```"[object Object]" is not a valid color or brush```

```jsx
import { PlatformColor } from 'react-native'

<SquircleView
      style={style}
      squircleParams={{
        cornerSmoothing: 0.7,
        cornerRadius: 30,
        fillColor: PlatformColor(`systemBlue`)
      }}
 />
 ```

**Comment by phamfoo** [comment]
This is [an issue from react-native-svg](https://github.com/react-native-svg/react-native-svg/issues/1391). Unfortunately, there doesn't seem to be a workaround. You'll have to wait until the issue is resolved.

**Comment by phamfoo** [comment]
It's not ideal, but you could apply the squircle shape to a normal `View` with [masked-view](https://github.com/react-native-masked-view/masked-view).

**Comment by cloudorbush** [comment]
For me the issue was fixed by just manually looked up the color codes.

```jsx

import { useColorScheme } from "react-native"

const theme = useColorScheme();

<SquircleView
      style={style}
      squircleParams={{
        cornerSmoothing: 1,
        cornerRadius: 20,
        fillColor : theme == 'light' ? 'rgb(0, 122, 255)' : 'rgb(10, 132, 255)'
      }}
/>

```
Works fine for my use case.

Thanks!

**Comment by phamfoo** [comment]
Glad you found a solution for your use case. Ideally, I think you still want to use `PlatformColor` when `react-native-svg` has support for it to make sure you get the correct native color.
