### ISSUE TITLE
How about mapping style attributes instead of squircle params?

### ISSUE THREAD

**Issue by finnp** [tienphaw/react-native-figma-squircle#5]
Not sure if it's worth the API break, but I'm wondering if it wouldn't by nicer to map style attributes like`borderColor` and `backgroundColor` instead of having a separate `squircleParams` attribute.

It would make it easier to use it as a drop in replacement when moving from Views to smooth corners.

In my project I'm using a wrapper like this (ignore the project specific defaults)
![image](https://user-images.githubusercontent.com/841788/128776090-3f063ae2-6a2b-4e37-901f-25d0f4e7e03b.png)

Just wondering what you think :)

**Comment by phamfoo** [comment]
Hi, thanks for the suggestion.
While it would be more convenient for the users, I don't want people to think they're using the same style props. The squircle params are used only to draw the SVG background. They're not native properties, so you can't do direct manipulation or animate them by creating an animated component.

**Comment by finnp** [comment]
Makes sense 👍
