### ISSUE TITLE
Doubt about corner with border

### ISSUE THREAD

**Issue by mjr** [tienphaw/react-native-figma-squircle#6]
It's possible?
<img width="481" alt="Screen Shot 2021-09-24 at 12 32 31" src="https://user-images.githubusercontent.com/9324986/134701772-702a4ad3-25f0-4145-a41d-ae2708369b34.png">

I tried but it doesn't apply to the border.
<img width="141" alt="Screen Shot 2021-09-24 at 12 37 29" src="https://user-images.githubusercontent.com/9324986/134702514-4b002396-8b4c-4699-8380-a4623abb7e15.png">

**Comment by phamfoo** [comment]
You can use `strokeColor` and `strokeWidth` to do that. Something like this should work:

```js
<SquircleView
  style={{ width: 300, height: 200 }}
  squircleParams={{
    fillColor: 'transparent',
    cornerSmoothing: 1,
    cornerRadius: 30,
    strokeColor: 'black',
    strokeWidth: 2,
  }}
/>

```

**Comment by mjr** [comment]
Worked exactly as expected, thank you very much.
