### ISSUE TITLE
Shadows not rendering on Android

### ISSUE THREAD

**Issue by alevkov** [tienphaw/react-native-figma-squircle#8]
### Versions

- "react-native": "0.64.3"
- "expo": "43.0.0"
- iOS 15
- Android 12.0

### Screenshots

- iOS

![Screen Shot 2021-12-17 at 9 37 43 PM](https://user-images.githubusercontent.com/8249463/146626261-f97ecf05-b648-4488-bea4-6eccf5ef9539.png)
![Screen Shot 2021-12-17 at 9 38 01 PM](https://user-images.githubusercontent.com/8249463/146626263-5b67ab01-6c95-471a-8e45-6c3386b88573.png)

- Android

![Screen Shot 2021-12-17 at 9 22 57 PM](https://user-images.githubusercontent.com/8249463/146626273-fba36264-354b-4cde-946b-b7543977074a.png)
![Screen Shot 2021-12-17 at 9 37 56 PM](https://user-images.githubusercontent.com/8249463/146626276-a435f44d-8aea-41ed-87c9-f3a5d8491358.png)

### Styles

```
style={{
  ...
  shadowColor: '#000',
  opacity: 0.4,
  shadowOffset: {
    width: 0,
    height: 5,
  },
  shadowOpacity: 0.34,
  shadowRadius: 6.27,

  elevation: 10,
}}
```

**Comment by phamfoo** [comment]
Can you try setting `borderRadius` in your style to the same value as the `cornerRadius`?

**Comment by alevkov** [comment]
@tienphaw worked like a charm. Thank you! 🙏
